pipeline {
  agent none
  stages {
    stage('Build') {
      agent {
        dockerfile {
          filename '.ci/Dockerfile'
          args '-v ${WORKSPACE}:/ws'
        }
      }
      steps {
        sh 'make clean'
        sh 'make'
      }
    }
    stage('Deploy') {
      agent {
        dockerfile {
          filename '.ci/Dockerfile.deploy'
          args '-v ${WORKSPACE}:/ws'
        }
      }
      options {
        skipDefaultCheckout()
      }
      steps {
        withCredentials([usernamePassword(credentialsId: 'jenkins-s3-creds',
            usernameVariable: 'USER', passwordVariable: 'PASS')]) {
          sh '''
            /ws/.ci/deploy.sh \
              $S3_HOST \
              $USER \
              $PASS \
              main.pdf \
              /$S3_BUCKET/ahepp/resume/latest/resume.pdf
          '''
          sh '''
            DESC=$(git describe)
            /ws/.ci/deploy.sh \
              $S3_HOST \
              $USER \
              $PASS \
              main.pdf \
              /$S3_BUCKET/ahepp/resume/resume-$DESC.pdf
          '''
        }
      }
    }
  }
}
