name: 'Generate resume preview and upload to S3'
on:
  pull_request:
    types: ['opened', 'edited']
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Resume
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make

      - name: Configure S3 Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Deploy to S3
        run: |
          aws s3 cp main.png s3://ahepp.dev/public/resume/previews/pr-${{ github.event.pull_request.number }}.png
