name: 'Generate resume preview and upload to S3'
on:
  pull_request:
    types: ['opened', 'synchronize']
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Resume
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make

      - name: Configure S3 Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Generate diff
        run: |
          ./.ci/scripts/do_diff.sh \
              ${{ github.event.pull_request.base.sha }}

      - name: Upload previews to S3
        run: |
          ./.ci/scripts/do_upload.sh \
              ${{ github.event.pull_request.base.sha }} \
              ${{ github.event.pull_request.head.sha }}
      - name: Comment on PR
        run: |
          ./.ci/scripts/do_comment.sh \
              ${{ secrets.GH_TOKEN }} \
              ${{ github.event.pull_request.number }} \
              ${{ github.event.pull_request.base.sha }} \
              ${{ github.event.pull_request.head.sha }}
